import { useEffect, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, ChevronRight, Menu, Search, Sparkles, X } from 'lucide-react';
import { subjects, bucketSubjects, steps, trustCards, quiz } from './content/homepage';
import curriculum from './content/master-curriculum.json';
import './styles.css';

const asset = '/eli/eli-hero.png';
const Button = ({ children, variant = 'primary', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: string }) => <button className={`button ${variant}`} {...props}>{children}</button>;

function Logo() { return <a className="logo" href="#top" aria-label="EliExplains.org home"><span className="logo-mark"><BookOpen size={20}/></span><span>Eli<span>Explains</span><small>.org</small></span></a>; }
function Header() {
  const [open, setOpen] = useState(false); const menu = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (e: KeyboardEvent) => e.key === 'Escape' && setOpen(false); addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, []);
  const links = [['Subjects', '/subjects'], ['Eli-10', '/#eli-ten'], ['Quick Quizzes', '/#quiz'], ['Study Tools', '/#how'], ['About', '/#about']];
  return <header><div className="nav container"><Logo/><nav className={open ? 'open' : ''} ref={menu} aria-label="Primary navigation">{links.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)}>{label}</a>)}<button className="search" aria-label="Search topics"><Search size={19}/></button><a className="button primary nav-cta" href="#subjects">Start Learning <ArrowRight size={17}/></a></nav><button className="menu-button" aria-expanded={open} aria-controls="primary-navigation" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></header>;
}
function Hero() { const surprise = () => document.getElementById('subjects')?.scrollIntoView({ behavior: 'smooth' }); return <section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><Sparkles size={16}/> The study sidekick you wish you had</p><h1>College concepts,<br/><em>explained twice.</em></h1><p className="lead">Learn the real college-level lesson. Then let Eli explain it so it finally clicks.</p><div className="actions"><a className="button primary" href="#subjects">Explore Subjects <ArrowRight size={18}/></a><Button variant="outline" onClick={surprise}>Surprise Me <span aria-hidden="true">✦</span></Button></div><div className="badges"><span><Check/> Open educational references</span><span><Check/> Built for college students</span><span><Check/> Sources on every topic</span></div></div><div className="eli-stage"><div className="dots"></div><div className="bubble">Let’s make this<br/>make sense.<i/></div><span className="doodle atom">✦</span><span className="doodle calc">＋</span><span className="doodle book">⌁</span><img src={asset} alt="Eli, the EliExplains college learning guide, pointing toward a speech bubble."/></div></div></section> }
function SubjectGrid() { return <section id="subjects" className="section subjects"><div className="container"><div className="section-head"><p className="eyebrow">Explore by subject</p><h2>What are we explaining today?</h2><p>Choose a subject, pick a topic, and learn it your way.</p></div><div className="subject-grid">{subjects.map(s => { const Icon = s.icon; return <a className={`subject-card ${s.accent}`} href={`/subjects/${s.slug}`} key={s.slug}><span className="subject-icon"><Icon/></span><div><h3>{s.title}</h3><p>{s.topicCount} topics</p></div><span className="explore">Explore <ChevronRight size={17}/></span></a> })}</div></div></section> }
function HowItWorks() { return <section id="how" className="section how"><div className="container"><div className="section-head centered"><p className="eyebrow">One topic. Two levels of explanation.</p><h2>How it works</h2></div><div className="steps">{steps.map(([num,title,text]) => <article className="step" key={num}><span className="step-num">{num}</span><div className="mini-illustration">{num === '01' ? '⌕' : num === '02' ? '✎' : '✦'}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section> }
function Featured() { return <section id="eli-ten" className="feature"><div className="container feature-grid"><div><p className="eyebrow gold-text">Featured Eli-10 explanation</p><h2>Correlation vs.<br/><em>causation</em></h2><div className="academic"><span>COLLEGE EXPLANATION</span><p>Correlation means two things change together. Causation means one thing directly causes the other.</p></div><a href="#quiz" className="button gold">Read the Eli-10 explanation <ArrowRight size={18}/></a></div><article className="comic"><p className="comic-tag">ELI-10 VERSION</p><div className="comic-scene"><span className="rain">☂</span><span className="rain two">• • •</span><img src={asset} alt="Eli illustration"/></div><div className="comic-bubble">Umbrellas do not cause rain. People use umbrellas because it rains!</div></article></div></section> }
function QuickQuiz() { const [selected, setSelected] = useState<number | null>(null); const [round, setRound] = useState(0); const result = selected === null ? '' : selected === quiz.correct ? 'correct' : 'incorrect'; return <section id="quiz" className="section quiz-section"><div className="container quiz-grid"><div><p className="eyebrow">A tiny practice moment</p><h2>Today’s 30-second<br/>brain boost</h2><p className="quiz-intro">Quick checks help turn a concept you recognize into one you can use.</p></div><article className="quiz-card" key={round}><span className="quiz-label">QUICK QUIZ</span><h3>{quiz.question}</h3><div className="answers">{quiz.answers.map((answer, i) => <button className={selected === i ? (i === quiz.correct ? 'correct' : 'incorrect') : ''} onClick={() => setSelected(i)} aria-pressed={selected === i} key={answer}>{answer}</button>)}</div><div className="quiz-feedback" aria-live="polite">{result === 'correct' ? <><strong>Correct! </strong>{quiz.explanation}</> : result === 'incorrect' ? <>Not quite—try again. {quiz.explanation}</> : 'Choose the answer that fits best.'}</div><Button variant="outline small" onClick={() => { setSelected(null); setRound(r => r + 1); }}>Try another question <ArrowRight size={16}/></Button></article></div></section> }
function Trust() { return <section id="about" className="section trust"><div className="container"><div className="section-head centered"><p className="eyebrow">Built for thoughtful learning</p><h2>Clear explanations. Real sources.</h2><p>Every topic includes references, licensing information, and a last-reviewed date.</p></div><div className="trust-grid">{trustCards.map(c => {const Icon = c.icon; return <article key={c.title}><span><Icon/></span><h3>{c.title}</h3><p>{c.text}</p></article>})}</div></div></section> }
function Footer() { return <footer><div className="container footer-grid"><div><Logo/><p>Making college concepts click — twice.</p><small>Clear lessons. Real sources. Student first.</small></div><div className="footer-links"><a href="#about">Sources & Licenses</a><a href="#about">Editorial Standards</a><a href="#about">Corrections</a><a href="#about">Accessibility</a><a href="mailto:hello@eliexplains.org">Contact</a></div><div className="footer-eli"><span>Keep learning!</span><img src={asset} alt="Eli waving"/></div></div><div className="container copyright">© {new Date().getFullYear()} EliExplains.org. Built for curious college minds.</div></footer> }
function SubjectsDirectory() { return <><Header/><main className="directory"><div className="container"><div className="section-head"><p className="eyebrow">The EliExplains curriculum</p><h1>Find your next <em>aha moment.</em></h1><p className="lead">A focused, searchable library for the concepts that show up in college courses.</p></div>{curriculum.collections.map(collection => <section className="collection" key={collection.slug}><h2>{collection.title}</h2><div className="directory-grid">{collection.subjectSlugs.map(slug => { const subject = curriculum.subjects.find(item => item.slug === slug)!; const count = subject.units.reduce((total, unit) => total + unit.topics.length, 0); return <a href={`/subjects/${subject.slug}`} key={subject.slug}><span>{subject.title}</span><small>{count} planned topics</small><ArrowRight size={18}/></a> })}</div></section>)}</div></main><Footer/></> }
function SubjectPage() { const slug = window.location.pathname.split('/')[2]; const featuredSubject = subjects.find(item => item.slug === slug); const bucketSubject = bucketSubjects.find(item => item.slug === slug); const plannedSubject = curriculum.subjects.find(item => item.slug === slug); if (!featuredSubject && !bucketSubject && !plannedSubject) return <><Header/><main className="route-page container"><p className="eyebrow">Page not found</p><h1>That subject is still getting its notes together.</h1><p className="lead">Return to the full subject explorer and choose a topic to begin.</p><a className="button primary" href="/subjects">Explore subjects <ArrowRight size={18}/></a></main><Footer/></>; const title = featuredSubject?.title ?? bucketSubject?.title ?? plannedSubject!.title; const Icon = featuredSubject?.icon ?? BookOpen; const isBucket = Boolean(bucketSubject); return <><Header/><main className="route-page container"><p className="eyebrow">Subject explorer</p><span className={`route-icon ${featuredSubject?.accent ?? 'teal'}`}><Icon/></span><h1>{title}</h1><p className="lead">{isBucket ? 'This Bucket A subject has a mapped MedMosa corpus. Publication remains gated until the source-rights review establishes an adaptation basis.' : 'This subject is part of the owner-authored EliExplains curriculum blueprint and is ready for future lesson authoring.'}</p><div className="route-note"><strong>{isBucket ? 'No migrated lessons are public yet.' : 'Lessons are planned, not yet published.'}</strong><br/>{isBucket ? <>The migration inventory preserves provenance, source hashes, review status, and the subject slug <code>{slug}</code> without exposing review-required lesson text.</> : <>{plannedSubject!.units.reduce((total, unit) => total + unit.topics.length, 0)} focused topic candidates are organized across {plannedSubject!.units.length} units.</>}</div><a className="button primary" href="/subjects">Back to all subjects <ArrowRight size={18}/></a></main><Footer/></> }
function App() { if (window.location.pathname === '/subjects') return <SubjectsDirectory/>; return window.location.pathname.startsWith('/subjects/') ? <SubjectPage/> : <><Header/><main><Hero/><SubjectGrid/><HowItWorks/><Featured/><QuickQuiz/><Trust/></main><Footer/></> };
document.title = 'EliExplains.org | College Concepts Explained Clearly';
document.querySelector('meta[name="description"]')?.setAttribute('content', 'Learn college-level concepts with clear academic explanations, then use Eli-10 to understand them in simple plain language.');
export default App;
import { createRoot } from 'react-dom/client'; createRoot(document.getElementById('root')!).render(<App/>);
